name = "pbth-entsoe-bridge"
main = "index.js"
compatibility_date = "2026-01-27"

# .workers.dev URL remains working
workers_dev = true
routes = [
	{ pattern = "entsoe.gruijter.org", custom_domain = true }
]

# R2 BINDING
[[r2_buckets]]
binding = "ENTSOE_PRICES_R2_BUCKET"
bucket_name = "entsoe-prices"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
persist = true
head_sampling_rate = 1
